version: '3.7'

volumes:
  database_data:
    driver: local
  database_log:
    driver: local
  database_secrets:
    driver: local

services:
  vehicle_db:
    image: mcr.microsoft.com/mssql/server
    container_name: vehicle_db
    user: root
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Test12345!
    volumes:
      - database_data:/var/opt/mssql/data
      - database_log:/var/opt/mssql/log
      - database_secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433

  vehicle_rabbit_mq:
    image: rabbitmq:3-management
    container_name: vehicle_rabbit_mq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672

  vehicle_mail_hog:
    image: mailhog/mailhog
    container_name: vehicle_mail_hog
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025

  vehicle_minio:
    image: minio/minio
    container_name: vehicle_minio
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Test12345!
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001

  vehicle_backend:
    image: vehicle/backend
    container_name: vehicle_backend
    depends_on:
      - vehicle_db
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    ports:
      - 4201:80

  vehicle_notifications_service:
    image: vehicle/notifications_service
    container_name: notifications_service
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    ports:
      - 4202:80

  vehicle_frontend:
    image: vehicle/frontend
    container_name: vehicle_frontend
    depends_on:
      - vehicle_backend
    restart: unless-stopped
    ports:
      - 4200:80
